name: Youtube Music Deployment

on:
   # opening a pull request to master and develop branch will be a trigger
  pull_request:
    branches:
      - dev
      - main
  # any code pushed to master and develop branch will also be a trigger
  push:
    branches:
      - main
      - deve

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2   

      - name: Git Pull on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZURI_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/music.zuri.chat
            git pull
            
            
            
            
            
            
